#!/bin/bash
#
# Usage: [ OPT=VAL ... ] sudo -u vagrant provision_vagrant
# 

quit() {
  echo $1
  exit 1
}

[ "$(whoami)" != "root" ] || quit "Don't run as root"

HOME=~

# Configuration variables

# The repo containing the share space stack.
export PROJECT_REPO=${PROJECT_REPO:-"https://github.com/alexjball/share-space.git"}

# Where the stack is checked out to.
export PROJECT_ROOT=${PROJECT_ROOT:-"$HOME/dev/share-space"}

# Source checkout

echo "Provisioning project in $PROJECT_ROOT"

git clone --recurse-submodules $PROJECT_REPO $PROJECT_ROOT || \
  quit "Couldn't check out project"

# Hand off to the stack repo

$PROJECT_ROOT/provision