#!/bin/bash
#
# Groups commands that run on the Share Space host.

quit() {
  echo $1
  exit 1
}

HOST_ROOT=$(dirname $(realpath $0))
PROJECT_ROOT=${PROJECT_ROOT:-"/home/vagrant/dev/share-space"}

mount-env() {
  cd $HOST_ROOT  

  local ENV=$1
  local GUEST=share-space-$ENV

  if ! mount | grep -q "$GUEST:$PROJECT_ROOT on $HOST_ROOT/$ENV"; then
    mkdir -p $ENV
    sudo mount -t nfs $GUEST:$PROJECT_ROOT $HOST_ROOT/$ENV
  fi
}

unmount-env() {
  local ENV=$1

  cd $HOST_ROOT
  sudo umount $2 $ENV
}

list-mounts() {
  mount | grep "share-space"
}

stack() {
  cd $HOST_ROOT

  local ENV=$1
  local CMD=$2
  local USAGE="Usage: run-host stack ENV {init|mount|build|up|down|status|unmount|halt|destroy}"

  if [ "$ENV" == "help" -o "$CMD" == "help" -o -z "$CMD" -o -z "$ENV" ]; then
    echo $USAGE
    exit
  fi

  case "$CMD" in
    init)
      vagrant up $ENV
      ;;
    halt)
      vagrant halt $ENV
      ;;
    destroy)
      vagrant destroy $3 $ENV
      ;;
    mount)
      vagrant up $ENV && \
        ./run-host mount-env $ENV
      ;;
    unmount)
      ./run-host unmount-env $ENV $3
      ;;
    *)
      vagrant provision $ENV --provision-with=stack-$CMD
  esac
}

help() {
  echo "Usage: $prog_name { $(join_by " | " ${CMDS[*]}) } [args ...]"
}

### Command Line Interface

join_by() {
  local d=$1; 
  shift; 
  echo -n "$1"; 
  shift; 
  printf "%s" "${@/#/$d}"
}

CMDS=(mount-env \
      unmount-env \
      list-mounts \
      stack \
      help)

prog_name=$0
cmd=$1
shift || true

for option in ${CMDS[*]}; do
  if [ "$cmd" == "$option" ]; then
    $cmd $@
    exit
  fi
done

echo "Unrecognized command $cmd"
help
exit 1
